name: "PR Issue Link"

on:
  pull_request:
    types: [opened]

jobs:
  link-pr-to-issue:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
      - name: Run action from local path
        uses: ./
